# Set this to false to pick up non-minified bootstrap css files.
# Useful in development. (Changes to this file requires restart of jekyll --server --auto)
bootstrap_min: false

navigation:
- text: Install
  dropdown:
  - text: Choose your Cucumber
    url: /install.html
  - divider
  - text: Install Cucumber-JVM
    url: /install-cucumber-jvm.html
  - text: Install Cucumber-Ruby
    url: /install-cucumber-ruby.html
  - text: Install Cucumber-Rails
    url: /install-cucumber-rails.html
  - text: Install Cucumber-JavaScript
    url: /install-cucumber-js.html
- text: Running
  url: /running.html
- text: Gherkin
  url: /gherkin.html
- text: API
  dropdown:
  - text: Step Definitions
    url: /step-definitions.html
  - text: Hooks
    url: /hooks.html
  - text: Transformation
    url: /transformation.html
  - divider: Cucumber-JVM
  - text: Dependency Injection
    url: /dependency-injection.html
- text: Learn more
  dropdown:
  - text: Browser Automation
    url: /browser-automation.html
  - text: Screenshots
    url: /screenshots.html
  - text: Databases
    url: /databases.html    
- text: Ecosystem
  dropdown:
  - text: Community Help
    url: /community-help.html
  - text: Source code
    url: /source-code.html
  - text: Editors and IDEs
    url: /editors-and-ides.html


pygments: true