# Set this to true to pick up non-minified bootstrap css files.
# Useful in development
bootstrap_min: false

navigation:
- text: Install
  dropdown:
  - text: General info
    url: /install.html
  - text: Install JVM
    url: /install-jvm.html
  - text: Install Ruby
    url: /install-ruby.html
  - text: Install Rails
    url: /install-rails.html
- text: Running
  url: /running.html
- text: Gherkin
  url: /gherkin.html
- text: API
  url: /api.html
- text: Tips
  url: /tips.html
  dropdown:
    - text: Web Apps
      url: /tips-webapps.html
    - text: Databases
      url: /tips-databases.html    
- text: Related Tools
  url: /tips.html

# Github overrides with this
safe: true
lsi: false
pygments: true
